import {defineArrayMember, defineField, defineType} from 'sanity'

export const serviceDefinition = defineType({
  name: 'serviceDefinition',
  title: 'Service definitions',
  type: 'document',
  groups: [
    {name: 'identity', title: 'Identity & navigation', default: true},
    {name: 'seo', title: 'SEO research'},
    {name: 'hero', title: 'Hero & intake'},
    {name: 'content', title: 'Service content'},
    {name: 'pricing', title: 'Pricing & FAQ'},
  ],
  fields: [
    defineField({name: 'serviceId', title: 'Service ID', type: 'number', group: 'identity', validation: (rule) => rule.required().integer().positive()}),
    defineField({name: 'name', title: 'Service name', type: 'string', group: 'identity', validation: (rule) => rule.required()}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', group: 'identity', options: {source: 'name', maxLength: 96}, validation: (rule) => rule.required()}),
    defineField({name: 'parentName', title: 'Parent category', type: 'string', group: 'identity'}),
    defineField({name: 'parentUrl', title: 'Parent URL', type: 'url', group: 'identity'}),
    defineField({name: 'hubUrl', title: 'Service hub URL', type: 'url', group: 'identity'}),
    defineField({name: 'primaryKeywords', title: 'Primary keywords', type: 'array', of: [defineArrayMember({type: 'string'})], group: 'seo'}),
    defineField({name: 'monthlySearchVolume', title: 'Monthly search volume', type: 'number', group: 'seo', validation: (rule) => rule.integer().min(0)}),
    defineField({name: 'secondaryKeywords', title: 'Secondary keywords', type: 'array', of: [defineArrayMember({type: 'string'})], group: 'seo'}),
    defineField({name: 'h1Prefix', title: 'H1 prefix', type: 'string', group: 'hero', validation: (rule) => rule.required()}),
    defineField({name: 'heroLede', title: 'Hero introduction', type: 'text', rows: 5, group: 'hero'}),
    defineField({name: 'secondaryCta', title: 'Secondary CTA', type: 'string', group: 'hero'}),
    defineField({name: 'issueQuestion', title: 'Intake question', type: 'string', group: 'hero'}),
    defineField({name: 'issueOptions', title: 'Intake options', type: 'array', of: [defineArrayMember({type: 'string'})], group: 'hero'}),
    defineField({name: 'typesHeading', title: 'Types heading', type: 'string', group: 'content'}),
    defineField({name: 'typesLede', title: 'Types introduction', type: 'text', group: 'content'}),
    defineField({name: 'types', title: 'Service types', type: 'array', of: [defineArrayMember({type: 'serviceType'})], group: 'content'}),
    defineField({name: 'typesFootnote', title: 'Types footnote', type: 'text', group: 'content'}),
    defineField({name: 'brandsHeading', title: 'Brands heading', type: 'string', group: 'content'}),
    defineField({name: 'brandsLede', title: 'Brands introduction', type: 'text', group: 'content'}),
    defineField({name: 'brands', title: 'Brands', type: 'array', of: [defineArrayMember({type: 'string'})], group: 'content'}),
    defineField({name: 'brandsNote', title: 'Brands note', type: 'text', group: 'content'}),
    defineField({name: 'whyHeading', title: 'Why-us heading', type: 'string', group: 'content'}),
    defineField({name: 'whyLede', title: 'Why-us introduction', type: 'text', group: 'content'}),
    defineField({name: 'whyItems', title: 'Why-us items', type: 'array', of: [defineArrayMember({type: 'titledBody'})], group: 'content'}),
    defineField({
      name: 'featuredCategory', title: 'Featured category', type: 'object', group: 'content',
      fields: [
        defineField({name: 'tag', title: 'Tag', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text'}),
        defineField({name: 'cta', title: 'CTA', type: 'string'}),
        defineField({name: 'url', title: 'URL', type: 'url'}),
      ],
    }),
    defineField({name: 'otherServices', title: 'Other services', type: 'array', of: [defineArrayMember({type: 'linkedService'})], group: 'content'}),
    defineField({
      name: 'pricing', title: 'Pricing section', type: 'object', group: 'pricing',
      fields: [
        defineField({name: 'heading', title: 'Heading', type: 'string'}),
        defineField({name: 'lede', title: 'Introduction', type: 'text'}),
        defineField({name: 'caption', title: 'Table caption', type: 'string'}),
        defineField({name: 'column1', title: 'Column 1', type: 'string'}),
        defineField({name: 'column2', title: 'Column 2', type: 'string'}),
        defineField({name: 'column3', title: 'Column 3', type: 'string'}),
        defineField({name: 'rows', title: 'Rows', type: 'array', of: [defineArrayMember({type: 'pricingRow'})]}),
        defineField({name: 'note', title: 'Note', type: 'text'}),
      ],
    }),
    defineField({name: 'faqs', title: 'Service FAQs', type: 'array', of: [defineArrayMember({type: 'faq'})], group: 'pricing'}),
    defineField({name: 'ctaHeading', title: 'Closing CTA heading', type: 'string', group: 'pricing'}),
    defineField({name: 'ctaBody', title: 'Closing CTA body', type: 'text', group: 'pricing'}),
  ],
  preview: {
    select: {title: 'name', subtitle: 'monthlySearchVolume'},
    prepare: ({title, subtitle}) => ({title, subtitle: subtitle ? `${Number(subtitle).toLocaleString()} monthly searches` : 'No volume'}),
  },
})
